networks:
  backend:
    driver: bridge

services:
  images-app:
    container_name: images-app
    build:
      context: .
      dockerfile: Dockerfile
    image: images-app-image
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - path: .env.example
        required: false
      - path: .env
        required: false
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_HOST: ${POSTGRES_HOST:?}
      POSTGRES_PORT: ${POSTGRES_PORT:?}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL:-}
      DJANGO_PORT: ${DJANGO_PORT:?}
    ports:
      - "${DJANGO_PORT}:8000"
    working_dir: /app
    volumes:
      - ./core:/app/core
    entrypoint:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:${DJANGO_PORT}
