networks:
  backend:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-image
    restart: always
    networks:
      - backend
    env_file:
      - path: .env.example
        required: false
      - path: .env
        required: false
    environment:
      DJANGO_PORT: ${DJANGO_PORT:?}
    ports:
      - "8080:80"