# Generated by Django 5.1.3 on 2024-12-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="ORMImages",
        ),
    ]
