# Generated by Django 5.1.3 on 2024-12-02 10:45

from django.db import migrations, models

import core.apps.images.enums


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_rename_images_ormimages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ormimages",
            old_name="encoded_image",
            new_name="base64_payload",
        ),
        migrations.AddField(
            model_name="ormimages",
            name="extension",
            field=models.CharField(
                choices=[("png", "png"), ("jpeg", "jpeg"), ("gif", "gif")],
                default=core.apps.images.enums.ImageExtension["jpeg"],
                max_length=5,
            ),
        ),
    ]
